export { site } from "./identity";
export {
  featuredProject,
  getProjectBySlug,
  getProjectRoute,
  projectPreviews,
  projectRoutes,
  projects,
  supportingProjects,
} from "./projects";
export {
  about,
  background,
  contact,
  hero,
  heroFacts,
  homeSections,
  homeNavSections,
  markPanels,
  navSections,
  runners,
  skillGroups,
  skills,
  tldr,
  work,
} from "./home";
export type {
  BackgroundEntry,
  Beat,
  ContentTone,
  FigureName,
  HeroFact,
  HomeSection,
  MarkPanel,
  Metric,
  PanelTone,
  Project,
  ProjectCaseStudySection,
  ProjectMetadata,
  ProjectRoute,
  ProjectSlug,
  RouteNavItem,
  Runner,
  SiteIdentity,
  Tldr,
  TldrRun,
} from "./types";
export { CONTENT_TONES, FIGURE_NAMES, HOME_ROUTE, PANEL_TONES, PROJECT_SLUGS } from "./types";
