/* All site copy, in one typed module.

   The previous site hardcoded content inside JSX, which is how it ended up with
   `link` fields defined on both projects and rendered on neither. Keeping copy
   in one place makes that class of drift visible: if a field exists here and no
   component reads it, that is a lint-visible unused property rather than a
   silent hole in the page. */

export type Beat = {
  label: string;
  heading: string;
  body: string;
};

export type Metric = {
  value: string;
  label: string;
};

/* Grounds that can carry body copy. sage, pink and forest all clear 7.0:1
   against their ink, which is what a three-step ink ramp needs. */
export type ContentTone = "sage" | "pink" | "forest";

/* Grounds that cannot. lilac and orange top out at 5.46:1 and 4.94:1 -- fine
   for display type, no headroom for a muted small-text step. Splitting the
   union is the guard: a Project cannot be given one of these by accident,
   because ProjectAct only accepts a ContentTone. See tokens.css for the
   measurements. */
export type PanelTone = "lilac" | "orange";

export type Tone = ContentTone | PanelTone;

/* A full-bleed colour panel carrying the mark and one display-size line, and
   nothing else. These are the page's rhythm: they break the run of dense acts
   the way the reference board breaks its grid. */
export type MarkPanel = {
  id: string;
  tone: PanelTone;
  /** Display-size. Deliberately the only text on the panel. */
  line: string;
};

export type Project = {
  id: string;
  /** Section numeral, e.g. "01". Drives the sticky rail and the heading order. */
  number: string;
  name: string;
  eyebrow: string;
  title: string;
  subtitle: string;
  tech: string[];
  metrics: Metric[];
  beats: Beat[];
  href: string;
  /** The act's ground. Re-points the whole palette for its subtree. */
  tone: ContentTone;
  figure: "coffeecat" | "diff" | "thread";
};

export const site = {
  name: "Kyrstin Kauchak",
  role: "Software Engineer II",
  location: "New York, NY",
  /* The tagline is the one line a recruiter reads before deciding to scroll.
     Naming the substrate (Spark, APIs, AWS) beats naming the adjectives. */
  tagline:
    "Backend engineer building distributed data systems — Spark ETL, performant APIs, and the observability to know they work.",
  email: "kauchakmk@gmail.com",
  github: "https://github.com/CoffeeCat0214",
  linkedin: "https://www.linkedin.com/in/kyrstin-mariko-kauchak/",
} as const;

export const projects: Project[] = [
  {
    id: "coffeecat",
    number: "01",
    name: "CoffeeCat",
    eyebrow: "Chrome Extension · Shipped",
    title: "A focus timer that never phones home.",
    subtitle:
      "A Manifest V3 Chrome extension: a pixel coffee cat that fills as a focus session runs. No backend, no analytics, no network calls of any kind.",
    tech: ["Manifest V3", "Vanilla JS", "chrome.storage.sync", "Service Worker", "Python tooling"],
    metrics: [
      { value: "0", label: "NETWORK CALLS" },
      { value: "0", label: "DEPENDENCIES" },
      { value: "MV3", label: "SERVICE WORKER" },
    ],
    beats: [
      {
        label: "The Problem",
        heading: "Focus tools watch you focus.",
        body: "Almost every productivity extension ships an account, a sync service, and an analytics SDK. That is three network dependencies and a privacy policy attached to a countdown timer. The interesting constraint was to find out what is actually left if you refuse all of it.",
      },
      {
        label: "The Approach",
        heading: "Make the privacy claim structural.",
        body: "State lives in chrome.storage.sync, so it follows the user's own Chrome profile without a server. The extension requests no host permissions, so 'it cannot read your pages' is enforced by the manifest rather than promised in a README. The artwork is generated by a Python tool into sprites and geometry, and a test asserts the site and the popup cannot drift apart.",
      },
      {
        label: "The Result",
        heading: "A privacy policy you can verify by reading the manifest.",
        body: "Zero runtime dependencies and zero network calls, which makes the strongest claim the product makes checkable in about thirty seconds. The same discipline produced the design system this site is built on.",
      },
    ],
    href: "https://github.com/CoffeeCat0214/CoffeeCat",
    /* The dark ground lands early, on the strongest project, where a visitor
       who bounces has still seen the page invert once. */
    tone: "forest",
    figure: "coffeecat",
  },
  {
    id: "codehusk",
    number: "02",
    name: "CodeHuskAI",
    eyebrow: "AI Refactoring Agent",
    title: "Repositories, rewritten with guardrails.",
    subtitle:
      "An AI-driven refactoring agent that analyzes repositories, enforces best practices, and suggests improvements without introducing breaking changes.",
    tech: ["Python", "Machine Learning", "NLP", "Git Integration", "CI/CD"],
    metrics: [
      { value: "AI", label: "ANALYSIS" },
      { value: "Git", label: "CONTEXT" },
      { value: "CI", label: "FEEDBACK" },
    ],
    beats: [
      {
        label: "The Problem",
        heading: "Automated refactors need context.",
        body: "The useful version of an AI code agent is not the one that rewrites everything. It is the one that understands repository shape, local conventions, and likely breakage before proposing changes.",
      },
      {
        label: "The Approach",
        heading: "Analyze first, suggest second.",
        body: "The agent is built around repository inspection, pattern recognition, and guarded suggestions that move through review instead of bypassing it.",
      },
      {
        label: "The Result",
        heading: "Faster cleanup without blind trust.",
        body: "CodeHuskAI frames refactoring as a structured assistant workflow: find opportunities, explain tradeoffs, and keep the final decision with the engineer.",
      },
    ],
    href: "https://github.com/CoffeeCat0214/CodeHuskAI",
    tone: "pink",
    figure: "diff",
  },
  {
    id: "cremeai",
    number: "03",
    name: "CremeAI",
    eyebrow: "Serverless Discord Bot",
    title: "A conversational bot with cloud-native bones.",
    subtitle:
      "An intelligent Discord chatbot on AWS Lambda with DynamoDB caching, rate limiting, and CloudWatch observability. Named after my cat, Crème Brûlée.",
    tech: ["AWS Lambda", "DynamoDB", "OpenAI API", "Discord API", "CloudWatch"],
    metrics: [
      { value: "AWS", label: "RUNTIME" },
      { value: "LLM", label: "ENGINE" },
      { value: "Cache", label: "LATENCY" },
    ],
    beats: [
      {
        label: "The Problem",
        heading: "Chatbots need more than a prompt.",
        body: "A useful Discord assistant has to handle latency, cost, API limits, and repeated requests while still feeling natural in conversation.",
      },
      {
        label: "The Approach",
        heading: "Serverless, observable, and bounded.",
        body: "Lambda handles event-driven execution, DynamoDB backs response caching, and rate limiting protects shared usage. CloudWatch gives the system a feedback loop.",
      },
      {
        label: "The Result",
        heading: "A playful interface on reliable infrastructure.",
        body: "The surface is a chat bot with a cat's name. Underneath it is a bounded, cached, instrumented service that degrades predictably when a dependency misbehaves.",
      },
    ],
    href: "https://github.com/CoffeeCat0214/CremeAI",
    tone: "sage",
    figure: "thread",
  },
];

/* Keyed by the id of the section they precede, so page.tsx stays declarative
   and the panels cannot drift away from the acts they punctuate. */
export const markPanels: Record<string, MarkPanel> = {
  coffeecat: { id: "panel-work", tone: "lilac", line: "Selected work" },
  experience: { id: "panel-background", tone: "orange", line: "Behind the work" },
};

/* Employer intentionally unnamed. The previous site carried "improved system
   reliability by 40%", which was placeholder text inherited from a deleted
   AI-generated "Senior Software Engineer, TechCorp Inc." stub -- it described no
   real work. Unverifiable numbers are worse than no numbers on a hiring page,
   so scope is described qualitatively instead. */
export const experience = [
  {
    role: "Software Engineer II",
    team: "Data Engineering",
    period: "2022 — Present",
    context: "High-traffic adtech platform",
    body: "Distributed Spark ETL pipelines and performant APIs serving high-traffic adtech workloads. Cloud-native AWS services, microservice architecture, observability instrumentation, and test-driven delivery across infrastructure and application layers.",
  },
];

export const education = [
  {
    role: "B.S. Software Engineering",
    team: "Miami University, Oxford OH",
    period: "2019 — 2022",
    context: "4.00 GPA · Summa Cum Laude",
    body: "",
  },
];

export const about = {
  heading: "Backend depth, product judgment.",
  /* Preserved from the previous site -- it was the one piece of genuinely
     resume-grade copy on it. */
  body: [
    "Backend Software Engineer with 3+ years designing scalable, data-driven systems in cloud-native environments. Proven track record building distributed Spark-based ETL pipelines and performant APIs used across high-traffic adtech platforms.",
    "Proficient in Java, Scala, and Python, with a focus on system efficiency, observability, and iterative, test-driven development. Comfortable across the stack — from infrastructure to application logic — and drawn to resilient microservices and ML-adjacent data systems.",
  ],
};

export const skills = [
  "Java",
  "Scala",
  "Python",
  "AWS",
  "Spark",
  "ETL",
  "Microservices",
  "API Design",
  "Test-Driven Development",
  "Cloud-Native",
  "Data Systems",
  "Observability",
];

export const navSections = [
  { id: "work", label: "Work" },
  { id: "experience", label: "Experience" },
  { id: "about", label: "About" },
  { id: "contact", label: "Contact" },
];
